"use client";

import { FadeIn, StaggerContainer, staggerChild } from "@/components/animations/fade-in";
import { challenges } from "@/data/site-data";
import { AlertTriangle, Ban } from "lucide-react";
import { motion } from "framer-motion";

export function ChallengesContent() {
  const challengeItems = challenges.filter((c) => c.type === "challenge");
  const limitationItems = challenges.filter((c) => c.type === "limitation");

  return (
    <div className="pt-24 lg:pt-32 pb-20">
      <div className="max-w-4xl mx-auto px-6 lg:px-8">
        <FadeIn>
          <span className="inline-block text-xs font-semibold uppercase tracking-[0.15em] text-accent mb-3">
            Transparency
          </span>
          <h1 className="text-4xl md:text-5xl font-semibold text-primary tracking-tight mb-6">
            Challenges & Limitations
          </h1>
          <p className="text-lg text-on-surface-variant leading-relaxed mb-16 max-w-3xl">
            An honest assessment of the technical challenges encountered during
            development and the current limitations of the system.
          </p>
        </FadeIn>

        {/* Challenges */}
        <FadeIn delay={0.1}>
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-xl bg-amber-50 flex items-center justify-center">
              <AlertTriangle className="w-5 h-5 text-amber-500" />
            </div>
            <h2 className="text-xl font-semibold text-primary">
              Technical Challenges
            </h2>
          </div>
        </FadeIn>

        <StaggerContainer className="space-y-4 mb-14">
          {challengeItems.map((item) => (
            <motion.div
              key={item.title}
              variants={staggerChild}
              className="bg-white rounded-xl p-6 border border-outline-variant/15 hover:border-amber-200/50 transition-colors duration-200"
            >
              <h3 className="text-sm font-semibold text-primary mb-2">
                {item.title}
              </h3>
              <p className="text-sm text-on-surface-variant leading-relaxed">
                {item.description}
              </p>
            </motion.div>
          ))}
        </StaggerContainer>

        {/* Limitations */}
        <FadeIn delay={0.2}>
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-xl bg-red-50 flex items-center justify-center">
              <Ban className="w-5 h-5 text-red-500" />
            </div>
            <h2 className="text-xl font-semibold text-primary">
              Known Limitations
            </h2>
          </div>
        </FadeIn>

        <StaggerContainer className="space-y-4">
          {limitationItems.map((item) => (
            <motion.div
              key={item.title}
              variants={staggerChild}
              className="bg-white rounded-xl p-6 border border-outline-variant/15 hover:border-red-200/50 transition-colors duration-200"
            >
              <h3 className="text-sm font-semibold text-primary mb-2">
                {item.title}
              </h3>
              <p className="text-sm text-on-surface-variant leading-relaxed">
                {item.description}
              </p>
            </motion.div>
          ))}
        </StaggerContainer>

        {/* Disclaimer */}
        <FadeIn delay={0.3}>
          <div className="mt-14 p-6 rounded-2xl bg-gradient-to-br from-primary to-primary-container text-white">
            <div className="flex items-start gap-3">
              <AlertTriangle className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
              <div>
                <h3 className="text-sm font-semibold mb-2">
                  Important Disclaimer
                </h3>
                <p className="text-sm text-white/70 leading-relaxed">
                  This project is developed for educational and research purposes
                  only and should not replace professional medical diagnosis.
                  Predictions generated by the model may contain inaccuracies due
                  to dataset limitations.
                </p>
              </div>
            </div>
          </div>
        </FadeIn>
      </div>
    </div>
  );
}
