export const siteConfig = {
  name: "Dervision",
  tagline: "AI-Powered Skin Disease Detection System",
  description:
    "Dervision uses Deep Learning and InceptionV3 architecture to classify skin conditions into 11 categories through an offline desktop software experience.",
  disclaimer:
    "This project is developed for educational and research purposes only and should not replace professional medical diagnosis. Predictions generated by the model may contain inaccuracies due to dataset limitations.",
};

export const navLinks = [
  { href: "/", label: "Home" },
  { href: "/about", label: "About" },
  { href: "/features", label: "Features" },
  { href: "/challenges", label: "Challenges" },
  { href: "/future", label: "Future Scope" },
  { href: "/contact", label: "Contact" },
];

export const features = [
  {
    title: "100% Offline Functionality",
    description:
      "Runs entirely on your local machine without any internet connection. Complete functionality available offline.",
    icon: "WifiOff" as const,
  },
  {
    title: "One-Click Execution",
    description:
      "Simply double-click the executable to launch. No complex setup, no dependencies to install manually.",
    icon: "MousePointerClick" as const,
  },
  {
    title: "Windows Compatible",
    description:
      "Built for Windows 10/11 with x64 CPU architecture. No GPU required for predictions.",
    icon: "Monitor" as const,
  },
  {
    title: "Lightweight Desktop App",
    description:
      "Packaged as a standalone desktop software using PyInstaller. Minimal resource usage.",
    icon: "Laptop" as const,
  },
  {
    title: "Private & Secure",
    description:
      "All data stays on your device. No cloud uploads, no data collection, complete privacy guaranteed.",
    icon: "ShieldCheck" as const,
  },
  {
    title: "AI Image Classification",
    description:
      "Powered by InceptionV3 deep learning model with transfer learning for accurate skin disease classification.",
    icon: "Brain" as const,
  },
  {
    title: "User-Friendly Interface",
    description:
      "Clean and intuitive CustomTkinter UI designed for ease of use by both professionals and general users.",
    icon: "Layout" as const,
  },
  {
    title: "11 Disease Categories",
    description:
      "Classifies skin conditions into 11 different categories with confidence scores for each prediction.",
    icon: "Grid3x3" as const,
  },
];

export const diseaseClasses = [
  {
    id: 1,
    name: "Eczema",
    description:
      "A chronic inflammatory skin condition causing dry, itchy, and inflamed patches on the skin.",
    severity: "Moderate",
    icon: "🔴",
  },
  {
    id: 2,
    name: "Melanoma",
    description:
      "The most serious type of skin cancer, developing from melanocyte cells that produce melanin pigment.",
    severity: "Critical",
    icon: "⚠️",
  },
  {
    id: 3,
    name: "Atopic Dermatitis",
    description:
      "A chronic form of eczema causing inflamed, itchy skin, often appearing in childhood.",
    severity: "Moderate",
    icon: "🟠",
  },
  {
    id: 4,
    name: "Basal Cell Carcinoma",
    description:
      "The most common form of skin cancer, typically appearing as a slightly transparent bump on sun-exposed skin.",
    severity: "High",
    icon: "🔶",
  },
  {
    id: 5,
    name: "Melanocytic Nevi",
    description:
      "Common moles formed by melanocyte clusters. Usually benign but should be monitored for changes.",
    severity: "Low",
    icon: "🟤",
  },
  {
    id: 6,
    name: "Benign Keratosis",
    description:
      "Non-cancerous skin growths including seborrheic keratoses and other benign lesions.",
    severity: "Low",
    icon: "🟡",
  },
  {
    id: 7,
    name: "Psoriasis / Lichen Planus",
    description:
      "Autoimmune conditions causing scaly, inflamed patches or purplish, itchy, flat-topped bumps.",
    severity: "Moderate",
    icon: "🟣",
  },
  {
    id: 8,
    name: "Seborrheic Keratosis",
    description:
      "Common non-cancerous skin growth appearing as waxy, brown, or black raised patches.",
    severity: "Low",
    icon: "🔵",
  },
  {
    id: 9,
    name: "Fungal Infections",
    description:
      "Skin infections caused by fungi, presenting as red, itchy, scaly, or ring-shaped patches.",
    severity: "Moderate",
    icon: "🟢",
  },
  {
    id: 10,
    name: "Viral Infections",
    description:
      "Skin manifestations of viral infections including warts, herpes simplex, and molluscum contagiosum.",
    severity: "Moderate",
    icon: "🔷",
  },
  {
    id: 11,
    name: "Healthy Skin",
    description:
      "Normal skin with no detected abnormalities or pathological findings in the analyzed image.",
    severity: "Normal",
    icon: "✅",
  },
];

export const techStack = {
  aiModel: [
    { name: "InceptionV3", description: "Deep learning architecture" },
    { name: "Transfer Learning", description: "Pre-trained model fine-tuning" },
    { name: "Python", description: "Programming language" },
  ],
  desktopApp: [
    { name: "Python", description: "Core programming language" },
    { name: "TensorFlow/Keras", description: "Deep learning framework" },
    { name: "CustomTkinter", description: "Modern UI framework" },
    { name: "PyInstaller", description: "Executable packaging tool" },
  ],
};

export const trainingDetails = {
  epochs: 20,
  validationPlateau: 13,
  totalClasses: 11,
  trainingImagesPerClass: 1000,
  validationImagesPerClass: 200,
  totalTrainingImages: 11000,
  totalValidationImages: 2200,
};

export const systemRequirements = [
  { label: "Operating System", value: "Windows 10 / 11" },
  { label: "CPU Architecture", value: "x64 (64-bit)" },
  { label: "GPU Required", value: "No" },
  { label: "Internet Required", value: "No" },
  { label: "Installation", value: "Double-click executable" },
  { label: "RAM", value: "4 GB minimum" },
];

export const challenges = [
  {
    title: "Dataset Collection",
    description:
      "Difficulty collecting balanced datasets across all 11 disease categories with sufficient quality.",
    type: "challenge" as const,
  },
  {
    title: "Image Quality Variations",
    description:
      "Medical images vary significantly in lighting, resolution, and capture conditions.",
    type: "challenge" as const,
  },
  {
    title: "Limited Dataset Accuracy",
    description:
      "Accuracy is inherently limited by the size and quality of the training dataset.",
    type: "challenge" as const,
  },
  {
    title: "Validation Accuracy Stagnation",
    description:
      "Validation accuracy plateaued after 13 epochs, indicating potential overfitting or dataset limitations.",
    type: "challenge" as const,
  },
  {
    title: "Not a Medical Replacement",
    description:
      "The system cannot replace professional medical diagnosis and should only be used as a supplementary tool.",
    type: "limitation" as const,
  },
  {
    title: "Accuracy Limitations",
    description:
      "Prediction accuracy is constrained by the quality and diversity of the training dataset.",
    type: "limitation" as const,
  },
  {
    title: "Further Validation Required",
    description:
      "Requires additional training, validation, and clinical testing before real-world deployment.",
    type: "limitation" as const,
  },
];

export const futurePlans = [
  {
    title: "Improved Dataset Quality",
    description:
      "Curate larger, higher-quality datasets with better class balance for improved accuracy.",
    icon: "Database" as const,
    status: "Planned",
  },
  {
    title: "Increased Model Accuracy",
    description:
      "Experiment with newer architectures and ensemble methods for better prediction performance.",
    icon: "TrendingUp" as const,
    status: "Research",
  },
  {
    title: "More Disease Classes",
    description:
      "Expand the classification model to cover additional dermatological conditions.",
    icon: "Plus" as const,
    status: "Planned",
  },
  {
    title: "Mobile Application",
    description:
      "Develop iOS and Android versions for portable skin analysis on smartphones.",
    icon: "Smartphone" as const,
    status: "Future",
  },
  {
    title: "Cloud Deployment",
    description:
      "Deploy the model on cloud infrastructure for web-based predictions without local installation.",
    icon: "Cloud" as const,
    status: "Future",
  },
  {
    title: "Cross-Platform Support",
    description:
      "Extend compatibility to macOS and Linux operating systems.",
    icon: "Globe" as const,
    status: "Future",
  },
  {
    title: "GPU Optimization",
    description:
      "Optimize inference pipeline for GPU acceleration and faster prediction times.",
    icon: "Zap" as const,
    status: "Research",
  },
  {
    title: "Real-Time Prediction",
    description:
      "Enable live camera feed analysis for real-time skin condition detection.",
    icon: "Camera" as const,
    status: "Future",
  },
];

export const teamMembers = [
  {
    name: "Dervision Team",
    role: "Final Year Engineering Students",
    department: "Computer Science & Engineering",
  },
];

export const workflowSteps = [
  {
    step: 1,
    title: "Capture Image",
    description:
      "Import a high-resolution photograph of the skin area to be analyzed.",
  },
  {
    step: 2,
    title: "AI Analysis",
    description:
      "The InceptionV3 neural network processes and analyzes the image against trained parameters.",
  },
  {
    step: 3,
    title: "Classification",
    description:
      "Receive a detailed probability breakdown across 11 distinct skin conditions.",
  },
];
